name: "WhatsApp Node Engine"
version: "1.1.2"
slug: "whatsapp_node_engine"
description: "Browserless WhatsApp Engine with AI and Native HA Auth"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
map:
  - config:rw
options: {}
schema: {}
ingress: true
ingress_port: 5002
panel_icon: mdi:whatsapp
panel_title: WhatsApp