name: "WhatsApp Node Engine"
version: "1.8.0"
slug: "whatsapp_node_engine"
description: "Browserless WhatsApp Engine with AI and Native HA Auth"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
map:
  - config:rw
options:
  password: ""
  debug_logging: false
  reset_database: false
  gemini_api_key: ""
schema:
  password: password?
  debug_logging: bool?
  reset_database: bool?
  gemini_api_key: password?
ingress: true
ingress_port: 5002
ingress_entry: /
panel_icon: mdi:whatsapp
panel_title: WhatsApp
ports:
  5002/tcp: 5002